// Language data for different countries and regions

export interface LanguageData {
  name: string
  nativeName?: string
  code?: string
  countries?: string[]
}

// Main languages by country
export const countryLanguages: Record<string, string[]> = {
  // North America
  USA: [
    "English",
    "Spanish",
    "French",
    "Chinese",
    "Tagalog",
    "Vietnamese",
    "Korean",
    "Russian",
    "Arabic",
    "Portuguese",
  ],
  Canada: [
    "English",
    "French",
    "Chinese",
    "Punjabi",
    "Spanish",
    "Arabic",
    "Tagalog",
    "Italian",
    "German",
    "Portuguese",
  ],
  Mexico: ["Spanish", "Nahuatl", "Maya", "Mixtec", "Zapotec", "Otomi", "English"],

  // Europe
  "United Kingdom": [
    "English",
    "Welsh",
    "Scots",
    "Scottish Gaelic",
    "Irish",
    "Polish",
    "Punjabi",
    "Urdu",
    "Bengali",
    "Arabic",
  ],
  France: [
    "French",
    "Occitan",
    "Breton",
    "Corsican",
    "Catalan",
    "Basque",
    "Arabic",
    "Portuguese",
    "Spanish",
    "Italian",
  ],
  Germany: ["German", "Turkish", "Kurdish", "Arabic", "Russian", "Polish", "Italian", "Greek", "Croatian", "English"],
  Spain: ["Spanish", "Catalan", "Galician", "Basque", "Valencian", "Aranese", "Arabic", "Romanian", "English"],
  Italy: ["Italian", "German", "French", "Slovene", "Ladin", "Friulian", "Sardinian", "Catalan", "Albanian", "Greek"],

  // Asia
  China: ["Mandarin", "Cantonese", "Wu", "Min", "Xiang", "Gan", "Hakka", "Tibetan", "Uyghur", "Mongolian"],
  India: ["Hindi", "Bengali", "Telugu", "Marathi", "Tamil", "Urdu", "Gujarati", "Kannada", "Odia", "Malayalam"],
  Japan: ["Japanese", "Ryukyuan", "Ainu", "Korean", "Chinese", "English"],
  Russia: ["Russian", "Tatar", "Chechen", "Bashkir", "Chuvash", "Ukrainian", "Avar", "Kazakh", "Yakut", "Udmurt"],

  // Africa
  Nigeria: ["English", "Hausa", "Yoruba", "Igbo", "Fulfulde", "Ijaw", "Kanuri", "Ibibio", "Tiv", "Edo"],
  Egypt: ["Arabic", "English", "French", "Nubian", "Beja", "Domari", "Siwi", "Coptic"],
  "South Africa": [
    "Zulu",
    "Xhosa",
    "Afrikaans",
    "English",
    "Northern Sotho",
    "Tswana",
    "Sotho",
    "Tsonga",
    "Swati",
    "Venda",
  ],

  // South America
  Brazil: [
    "Portuguese",
    "German",
    "Italian",
    "Japanese",
    "Spanish",
    "English",
    "Hunsrik",
    "Nheengatu",
    "Baniwa",
    "Tucano",
  ],
  Argentina: ["Spanish", "Italian", "Arabic", "German", "Guaraní", "Mapudungun", "Quechua", "Welsh", "English"],
  Colombia: ["Spanish", "English", "Wayuu", "Palenquero", "Romani", "Embera", "Sikuani", "Guambiano", "Tucano"],

  // Oceania
  Australia: [
    "English",
    "Mandarin",
    "Arabic",
    "Cantonese",
    "Vietnamese",
    "Italian",
    "Greek",
    "Tagalog",
    "Hindi",
    "Spanish",
  ],
  "New Zealand": ["English", "Māori", "Samoan", "Hindi", "Mandarin", "French", "Yue", "German", "Tongan", "Tagalog"],
}

// Languages by state/province for specific countries
export const stateLanguages: Record<string, Record<string, string[]>> = {
  USA: {
    California: [
      "English",
      "Spanish",
      "Chinese",
      "Tagalog",
      "Vietnamese",
      "Korean",
      "Armenian",
      "Persian",
      "Japanese",
      "Russian",
    ],
    Texas: ["English", "Spanish", "Vietnamese", "Chinese", "Tagalog", "Arabic", "Urdu", "French", "Korean", "German"],
    "New York": [
      "English",
      "Spanish",
      "Chinese",
      "Russian",
      "Yiddish",
      "Bengali",
      "Korean",
      "Haitian Creole",
      "Italian",
      "Arabic",
    ],
    Florida: [
      "English",
      "Spanish",
      "Haitian Creole",
      "Portuguese",
      "French",
      "German",
      "Italian",
      "Arabic",
      "Vietnamese",
      "Russian",
    ],
    Illinois: ["English", "Spanish", "Polish", "Chinese", "Tagalog", "Arabic", "Korean", "Russian", "Urdu", "Gujarati"],
    "New Mexico": [
      "English",
      "Spanish",
      "Navajo",
      "Pueblo",
      "Apache",
      "German",
      "Vietnamese",
      "Chinese",
      "Tagalog",
      "Korean",
    ],
    Hawaii: [
      "English",
      "Hawaiian",
      "Japanese",
      "Ilocano",
      "Tagalog",
      "Chinese",
      "Korean",
      "Samoan",
      "Tongan",
      "Spanish",
    ],
    Louisiana: [
      "English",
      "French",
      "Spanish",
      "Vietnamese",
      "Chinese",
      "Arabic",
      "Tagalog",
      "Korean",
      "German",
      "Italian",
    ],
    Alaska: [
      "English",
      "Yupik",
      "Inupiaq",
      "Athabaskan",
      "Aleut",
      "Tlingit",
      "Haida",
      "Tsimshian",
      "Spanish",
      "Tagalog",
    ],
  },
  Canada: {
    Quebec: [
      "French",
      "English",
      "Arabic",
      "Spanish",
      "Italian",
      "Mandarin",
      "Creole",
      "Greek",
      "Portuguese",
      "Russian",
    ],
    Ontario: [
      "English",
      "French",
      "Mandarin",
      "Cantonese",
      "Punjabi",
      "Spanish",
      "Italian",
      "German",
      "Portuguese",
      "Urdu",
    ],
    "British Columbia": [
      "English",
      "Mandarin",
      "Cantonese",
      "Punjabi",
      "Tagalog",
      "Korean",
      "Spanish",
      "French",
      "German",
      "Japanese",
    ],
    Alberta: [
      "English",
      "French",
      "Mandarin",
      "Cantonese",
      "Punjabi",
      "Tagalog",
      "Spanish",
      "German",
      "Ukrainian",
      "Arabic",
    ],
    Manitoba: [
      "English",
      "French",
      "German",
      "Ukrainian",
      "Tagalog",
      "Punjabi",
      "Spanish",
      "Mandarin",
      "Cantonese",
      "Cree",
    ],
  },
  India: {
    "Tamil Nadu": ["Tamil", "English", "Telugu", "Kannada", "Malayalam", "Hindi", "Urdu", "Sanskrit"],
    Maharashtra: ["Marathi", "Hindi", "English", "Urdu", "Gujarati", "Kannada", "Telugu", "Konkani"],
    "West Bengal": ["Bengali", "Hindi", "English", "Nepali", "Urdu", "Santali", "Odia", "Punjabi"],
    Karnataka: ["Kannada", "English", "Telugu", "Tamil", "Hindi", "Marathi", "Tulu", "Konkani"],
    Gujarat: ["Gujarati", "Hindi", "English", "Sindhi", "Marathi", "Urdu", "Punjabi", "Kutchi"],
  },
  China: {
    Beijing: ["Mandarin", "English", "Cantonese", "Japanese", "Korean", "Russian", "French", "German"],
    Shanghai: ["Mandarin", "Shanghainese", "English", "Cantonese", "Japanese", "Korean", "French", "German"],
    Guangdong: ["Cantonese", "Mandarin", "English", "Hakka", "Teochew", "Japanese", "Korean", "Vietnamese"],
    "Hong Kong": ["Cantonese", "English", "Mandarin", "Hakka", "Teochew", "Tagalog", "Indonesian", "Japanese"],
    Tibet: ["Tibetan", "Mandarin", "English", "Nepali", "Hindi", "Bhutanese", "Sikkimese", "Ladakhi"],
  },
  Germany: {
    Bavaria: ["German", "Bavarian", "English", "Turkish", "Italian", "Russian", "Romanian", "Polish"],
    Berlin: ["German", "English", "Turkish", "Arabic", "Russian", "Polish", "Vietnamese", "Italian"],
    "North Rhine-Westphalia": ["German", "Turkish", "English", "Arabic", "Polish", "Russian", "Italian", "Greek"],
    Saxony: ["German", "Sorbian", "English", "Russian", "Polish", "Vietnamese", "Turkish", "Arabic"],
  },
  Australia: {
    "New South Wales": ["English", "Mandarin", "Arabic", "Cantonese", "Vietnamese", "Greek", "Italian", "Hindi"],
    Victoria: ["English", "Mandarin", "Italian", "Greek", "Vietnamese", "Cantonese", "Arabic", "Turkish"],
    Queensland: ["English", "Mandarin", "Cantonese", "Vietnamese", "Italian", "Tagalog", "Spanish", "Korean"],
    "Western Australia": ["English", "Mandarin", "Italian", "Vietnamese", "Cantonese", "Arabic", "Malay", "German"],
  },
  Brazil: {
    "São Paulo": ["Portuguese", "Italian", "Japanese", "Spanish", "German", "Arabic", "Chinese", "Korean"],
    "Rio de Janeiro": ["Portuguese", "English", "Spanish", "French", "Italian", "German", "Japanese", "Arabic"],
    Amazonas: ["Portuguese", "Spanish", "Nheengatu", "Tucano", "Baniwa", "Tikuna", "Yanomami", "English"],
    "Rio Grande do Sul": ["Portuguese", "German", "Italian", "Spanish", "Polish", "Ukrainian", "Japanese", "Arabic"],
  },
}

// Default languages for continents if country not found
export const continentalLanguages: Record<string, string[]> = {
  Africa: [
    "Arabic",
    "Swahili",
    "Hausa",
    "Amharic",
    "Yoruba",
    "Oromo",
    "Igbo",
    "Zulu",
    "Shona",
    "English",
    "French",
    "Portuguese",
  ],
  Asia: [
    "Mandarin",
    "Hindi",
    "Arabic",
    "Bengali",
    "Japanese",
    "Punjabi",
    "Vietnamese",
    "Korean",
    "Tamil",
    "Urdu",
    "Thai",
    "Persian",
  ],
  Europe: [
    "English",
    "Russian",
    "German",
    "French",
    "Italian",
    "Spanish",
    "Polish",
    "Ukrainian",
    "Romanian",
    "Dutch",
    "Greek",
    "Portuguese",
  ],
  "North America": [
    "English",
    "Spanish",
    "French",
    "Haitian Creole",
    "Navajo",
    "Dakota",
    "Yupik",
    "Cherokee",
    "Ojibwe",
  ],
  "South America": [
    "Spanish",
    "Portuguese",
    "Quechua",
    "Guaraní",
    "Aymara",
    "Mapudungun",
    "Tupi",
    "English",
    "Dutch",
    "French",
  ],
  Oceania: [
    "English",
    "Tok Pisin",
    "Māori",
    "Samoan",
    "Fijian",
    "Tongan",
    "Tahitian",
    "Hawaiian",
    "Marshallese",
    "Palauan",
  ],
}

// Helper function to get languages by country
export const getLanguagesByCountry = (country: string): string[] => {
  return countryLanguages[country] || []
}

// Helper function to get languages by state
export const getLanguagesByState = (country: string, state: string): string[] => {
  return stateLanguages[country]?.[state] || getLanguagesByCountry(country)
}

// List of all languages with additional metadata
export const languages: LanguageData[] = [
  { name: "English", nativeName: "English", code: "en" },
  { name: "Spanish", nativeName: "Español", code: "es" },
  { name: "French", nativeName: "Français", code: "fr" },
  { name: "German", nativeName: "Deutsch", code: "de" },
  { name: "Chinese", nativeName: "中文", code: "zh" },
  { name: "Mandarin", nativeName: "普通话", code: "zh-CN" },
  { name: "Cantonese", nativeName: "廣東話", code: "zh-HK" },
  { name: "Japanese", nativeName: "日本語", code: "ja" },
  { name: "Korean", nativeName: "한국어", code: "ko" },
  { name: "Russian", nativeName: "Русский", code: "ru" },
  { name: "Arabic", nativeName: "العربية", code: "ar" },
  { name: "Hindi", nativeName: "हिन्दी", code: "hi" },
  { name: "Portuguese", nativeName: "Português", code: "pt" },
  { name: "Bengali", nativeName: "বাংলা", code: "bn" },
  { name: "Italian", nativeName: "Italiano", code: "it" },
  { name: "Turkish", nativeName: "Türkçe", code: "tr" },
  { name: "Vietnamese", nativeName: "Tiếng Việt", code: "vi" },
  { name: "Polish", nativeName: "Polski", code: "pl" },
  { name: "Ukrainian", nativeName: "Українська", code: "uk" },
  { name: "Dutch", nativeName: "Nederlands", code: "nl" },
  { name: "Greek", nativeName: "Ελληνικά", code: "el" },
  { name: "Thai", nativeName: "ไทย", code: "th" },
  { name: "Tagalog", nativeName: "Tagalog", code: "tl" },
  { name: "Swahili", nativeName: "Kiswahili", code: "sw" },
  { name: "Malay", nativeName: "Bahasa Melayu", code: "ms" },
  { name: "Indonesian", nativeName: "Bahasa Indonesia", code: "id" },
  { name: "Hebrew", nativeName: "עברית", code: "he" },
  { name: "Swedish", nativeName: "Svenska", code: "sv" },
  { name: "Norwegian", nativeName: "Norsk", code: "no" },
  { name: "Danish", nativeName: "Dansk", code: "da" },
  { name: "Finnish", nativeName: "Suomi", code: "fi" },
  { name: "Czech", nativeName: "Čeština", code: "cs" },
  { name: "Hungarian", nativeName: "Magyar", code: "hu" },
  { name: "Romanian", nativeName: "Română", code: "ro" },
  { name: "Bulgarian", nativeName: "Български", code: "bg" },
  { name: "Serbian", nativeName: "Српски", code: "sr" },
  { name: "Croatian", nativeName: "Hrvatski", code: "hr" },
  { name: "Slovak", nativeName: "Slovenčina", code: "sk" },
  { name: "Slovenian", nativeName: "Slovenščina", code: "sl" },
  { name: "Lithuanian", nativeName: "Lietuvių", code: "lt" },
  { name: "Latvian", nativeName: "Latviešu", code: "lv" },
  { name: "Estonian", nativeName: "Eesti", code: "et" },
  { name: "Albanian", nativeName: "Shqip", code: "sq" },
  { name: "Macedonian", nativeName: "Македонски", code: "mk" },
  { name: "Bosnian", nativeName: "Bosanski", code: "bs" },
  { name: "Icelandic", nativeName: "Íslenska", code: "is" },
  { name: "Maltese", nativeName: "Malti", code: "mt" },
  { name: "Welsh", nativeName: "Cymraeg", code: "cy" },
  { name: "Irish", nativeName: "Gaeilge", code: "ga" },
  { name: "Scottish Gaelic", nativeName: "Gàidhlig", code: "gd" },
  { name: "Basque", nativeName: "Euskara", code: "eu" },
  { name: "Catalan", nativeName: "Català", code: "ca" },
  { name: "Galician", nativeName: "Galego", code: "gl" },
  { name: "Luxembourgish", nativeName: "Lëtzebuergesch", code: "lb" },
  { name: "Frisian", nativeName: "Frysk", code: "fy" },
  { name: "Breton", nativeName: "Brezhoneg", code: "br" },
  { name: "Corsican", nativeName: "Corsu", code: "co" },
  { name: "Occitan", nativeName: "Occitan", code: "oc" },
  { name: "Māori", nativeName: "Te Reo Māori", code: "mi" },
  { name: "Hawaiian", nativeName: "ʻŌlelo Hawaiʻi", code: "haw" },
  { name: "Samoan", nativeName: "Gagana Sāmoa", code: "sm" },
  { name: "Tongan", nativeName: "Lea Fakatonga", code: "to" },
  { name: "Fijian", nativeName: "Na Vosa Vakaviti", code: "fj" },
]

export default {
  countryLanguages,
  stateLanguages,
  continentalLanguages,
  getLanguagesByCountry,
  getLanguagesByState,
  languages,
}
